In [1]:
import numpy as np

from framework.Tensor import Tensor
from framework.SGD import SGD
from framework.Sequential import Sequential
from framework.Linear import Linear
from framework.Embedding import Embedding
from framework.Tanh import Tanh
from framework.Sigmoid import Sigmoid
from framework.MSELoss import MSELoss

In [2]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
identity[np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 0]]
)]

array([[[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.]]])

In [4]:
 = Tensor(np.eye(5), autograd=True)
print(.data)

.index_select(Tensor([[1, 2, 3], [2, 3, 4]])).backward()

print()
print(.grad.data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [5]:
np.random.seed(42)

x = Tensor(np.array([1, 2, 1, 2]), autograd=True)
y = Tensor(np.array([[0], [1], [0], [1]]), autograd=True)

model = Sequential([
    Embedding(vocab_size=5, dim=3),
    Tanh(),
    Linear(3, 1),
    Sigmoid()
])
loss = MSELoss()
optimizer = SGD(params=model.get_params(), alpha=0.5)

for i in range(10):  # epochs
    y_hat = model.forward(x)
    l = loss.forward(y_hat, y)
    l.backward(Tensor(np.ones_like(l.data)))
    optimizer.step()
    print(l.data[0])

0.9987000994300574
0.9101428396267963
0.8129082684736105
0.6857939691454805
0.531494274065172
0.3784952798902772
0.25874454794634577
0.17964911573984998
0.13036886191413982
0.09915050683415495
