In [1]:
import numpy as np

from framework.Tensor import Tensor
from framework.SGD import SGD
from framework.Sequential import Sequential
from framework.Linear import Linear
from framework.Embedding import Embedding
from framework.Tanh import Tanh
from framework.Sigmoid import Sigmoid
from framework.MSELoss import MSELoss
from framework.CrossEntropyLoss import CrossEntropyLoss

In [2]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
identity[np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 0]]
)]

array([[[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.]]])

In [4]:
x = Tensor(np.eye(5), autograd=True)
print(x.data)

x.index_select(Tensor([[1, 2, 3], [2, 3, 4]])).backward()

print()
print(x.grad.data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [8]:
# MSE Loss function (бинарная классификация)
np.random.seed(0)

x = Tensor(np.array([1, 2, 1, 2]), autograd=True)
y = Tensor(np.array([[0], [1], [0], [1]]), autograd=True)

model = Sequential([
    Embedding(vocab_size=5, dim=3),
    Tanh(),
    Linear(3, 1),
    Sigmoid()
])
loss = MSELoss()
optimizer = SGD(params=model.get_params(), alpha=0.5)

for i in range(10):  # epochs
    y_hat = model.forward(x)
    l = loss.forward(y_hat, y)
    l.backward(Tensor(np.ones_like(l.data)))
    optimizer.step()
    print(l.data[0])

0.9399769833060094
0.7767629507851901
0.6167738616356688
0.46103692997029144
0.3314775513353698
0.23856396660909968
0.17660672959383822
0.1355809593270884
0.10771797427980923
0.08811936379792203


In [9]:
# Cross Entropy Loss function (многоклассовая классификация)
np.random.seed(0)

x = Tensor(np.array([1, 2, 1, 2]), autograd=True)
y = Tensor(np.array([0, 1, 0, 1]), autograd=True)

model = Sequential([
    Embedding(3, 3),
    Tanh(),
    Linear(3, 4)
])
loss = CrossEntropyLoss()
optimizer = SGD(params=model.get_params(), alpha=0.1)

for i in range(10):
    y_hat = model.forward(x)
    l = loss.forward(y_hat, y)
    l.backward(Tensor(np.ones_like(l.data)))
    optimizer.step()
    print(l.data)

1.3980002482441969
1.2735653055576115
1.1686996889127599
1.0759609832981503
0.9895117043003762
0.9050423419228637
0.8199340491486635
0.7335155973842289
0.6470999402404227
0.5634775329624433
