# Матричное умножение в NumPy (`A.dot(B)`)

Матричное умножение — это операция, при которой строки первой матрицы `A` умножаются на столбцы второй матрицы `B`.

Если `A` — матрица **размера (m × n)**, а `B` — матрица **размера (n × p)**, то результат `A.dot(B)` будет **матрицей (m × p)**.

Элемент результирующей матрицы `C` на позиции `(i, j)` вычисляется как:

$$
C_{i,j} = \sum_{k} A_{i,k} \cdot B_{k,j}
$$


In [80]:
import numpy as np

In [81]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)
print((1 * 5) + (2 * 7))
print((1 * 6) + (2 * 8))
print((3 * 5) + (4 * 7))
print((3 * 6) + (4 * 8))
A.dot(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
19
22
43
50


array([[19, 22],
       [43, 50]])

In [82]:
# Создание массивов с нулями, единицами и случайными значениями
print(np.zeros((2, 3)))  # Матрица 2x3 из нулей
print(np.ones((3, 3)))  # Матрица 3x3 из единиц
print(np.random.rand(2, 2))  # Случайная матрица 2x2 (0-1)
print(np.random.randn(3, 3))  # Матрица 3x3 из случайных значений нормального распределения

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.18182497 0.18340451]
 [0.30424224 0.52475643]]
[[-1.72491783 -0.56228753 -1.01283112]
 [ 0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282 ]]


In [83]:
# Создание массива с линейными значениями
print(np.linspace(0, 10, 5))  # 5 чисел от 0 до 10
print(np.arange(0, 10, 2))  # Числа от 0 до 10 с шагом 2

[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]


In [84]:
# Изменение формы массива (Reshape)
a = np.arange(1, 10)  # [1, 2, ..., 9]
print(a.reshape(3, 3))  # Преобразование в матрицу 3x3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
# Арифметические операции (поэлементные)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Сложение
print(a - b)  # Вычитание
print(a * b)  # Поэлементное умножение
print(a / b)  # Поэлементное деление
print(a ** 2)  # Возведение в квадрат

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [86]:
# Операции с матрицами
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A.dot(B))  # Матричное умножение
print(A @ B)  # Альтернативный способ

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [87]:
# Статистические функции
a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))  # Среднее
print(np.std(a))  # Стандартное отклонение
print(np.var(a))  # Дисперсия
print(np.min(a))  # Минимум
print(np.max(a))  # Максимум
print(np.sum(a))  # Сумма всех элементов

3.0
1.4142135623730951
2.0
1
5
15


In [88]:
# Индексация и срезы
a = np.array([10, 20, 30, 40, 50])
print(a[0])  # Первый элемент
print(a[-1])  # Последний элемент
print(a[1:4])  # Подмассив с 1 по 3 элемент

10
50
[20 30 40]


In [89]:
# Работа с многомерными массивами
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A[0, 1])  # Элемент из 1-го ряда, 2-й столбец (2)
print(A[:, 1])  # Все элементы второго столбца
print(A[1, :])  # Все элементы второй строки


2
[2 5 8]
[4 5 6]


In [90]:
# Булева индексация (Фильтрация данных)
a = np.array([10, 20, 30, 40, 50])

print(a[a > 25])  # Все элементы > 25

[30 40 50]


In [91]:
# Генерация случайных данных (для ML)
np.random.seed(42)  # Фиксируем генератор для воспроизводимости
data = np.random.randn(10)  # 1000 значений из нормального распределения
data

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [92]:
# Работа с NaN и бесконечностями
a = np.array([1, 2, np.nan, 4, np.inf])

print(np.isnan(a))  # Проверка на NaN
print(np.isinf(a))  # Проверка на бесконечность

# Заменяем NaN на среднее значение массива
a[np.isnan(a)] = np.nanmean(a)

[False False  True False False]
[False False False False  True]
