# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__, np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.12
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/s3/vj2zzxnd01l53jcjc04ljvz80000gn/T/build-env-uj2x

('2.2.3', None)

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
np.zeros(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.array(range(10, 50))
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a = np.array([1, 2, 3])
b = a[::-1]
b


array([3, 2, 1])

r#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
np.array([1, 2, 0, 0, 4, 0]).nonzero()
np.where(np.array([1, 2, 0, 0, 4, 0]) != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)  # Поддерживает смещение
np.identity(3)  # Может быть не квадратной

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random((3, 3, 3))

array([[[0.33105328, 0.60718204, 0.42794544],
        [0.81012399, 0.42519807, 0.59424445],
        [0.30520448, 0.26608723, 0.21069349]],

       [[0.0236519 , 0.94177355, 0.39942095],
        [0.06820526, 0.57337916, 0.12054767],
        [0.29935972, 0.86463173, 0.07645291]],

       [[0.0038506 , 0.60499393, 0.47272681],
        [0.25881152, 0.05700233, 0.30915921],
        [0.22784444, 0.3515456 , 0.79411256]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.random((10, 10))
a.min(), a.max()

(np.float64(0.006153183464551182), np.float64(0.9794618402522417))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.random.random(30).mean()

np.float64(0.48427867634919497)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a = np.zeros((5, 5), dtype=int)
a[0][0:5] = 1
a[4][0:5] = 2
a[:, 0] = 3
a[:, 4] = 4

b = np.ones((5, 5), dtype=int)
b[1:-1, 1:-1] = 0
a, b

(array([[3, 1, 1, 1, 4],
        [3, 0, 0, 0, 4],
        [3, 0, 0, 0, 4],
        [3, 0, 0, 0, 4],
        [3, 2, 2, 2, 4]]),
 array([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]]))

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
np.pad(np.ones((5, 5), dtype=int), pad_width=1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)  # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)  # False
print(np.nan - np.nan)  # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)  # False

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a = np.zeros((8, 8))
a[::2, 1::2] = 1
a[1::2, 0::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
a = np.arange(6 * 7 * 8).reshape(6, 7, 8)
a[np.unravel_index(100, (6, 7, 8))] == 100

np.True_

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
a = np.array([[1, 0], [0, 1]])
a = np.tile(a, 4)
np.tile(a.T, 4)

np.tile(np.array([[1, 0], [0, 1]]), (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.random.rand(5, 5)
(a - a.min()) / a.std()

array([[0.27515002, 1.556921  , 0.        , 1.8216543 , 0.25442081],
       [0.02055684, 1.30348828, 2.85539555, 2.08033773, 2.97569194],
       [0.24530595, 1.77600354, 2.01135924, 2.38796801, 0.18415018],
       [2.89611844, 2.72764758, 0.2439396 , 0.5761422 , 0.84041859],
       [0.41557002, 0.60991589, 1.0945743 , 0.07577246, 1.12782745]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

dtype([('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.random.rand(15).reshape(5, 3)
b = np.random.rand(6).reshape(3, 2)
a @ b

array([[0.74006514, 0.91224871],
       [0.89419042, 0.62226656],
       [1.31254027, 0.37818443],
       [0.44137009, 0.10854853],
       [0.76096373, 0.21382953]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.array(range(0, 10))
a[(a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5), -1))
from numpy import *

print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.array([1, 2, 3])
print(Z ** Z)
print(2 << Z >> 2)
print(Z < - Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z<Z>Z)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/v5/htg9fq1n04z2dcqyv_p6f3cw0000gn/T/ipykernel_81043/1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/v5/htg9fq1n04z2dcqyv_p6f3cw0000gn/T/ipykernel_81043/1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/v5/htg9fq1n04z2dcqyv_p6f3cw0000gn/T/ipykernel_81043/1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
a = np.random.rand(10)
round(a, 1)

array([0.3, 0.6, 0.5, 1. , 0.1, 0.2, 0. , 0.5, 0. , 0.8])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
a = np.array(range(5))
b = np.array(range(3, 7))
np.intersect1d(a, b, return_indices=True)


(array([3, 4]), array([3, 4]), array([0, 1]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
import warnings

warnings.filterwarnings("ignore")  # Отключает все предупреждения
warnings.filterwarnings("default")  # Включаем обратно все предупреждения


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/v5/htg9fq1n04z2dcqyv_p6f3cw0000gn/T/ipykernel_81043/2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
today = np.datetime64('today', 'D')  # Сегодня
yesterday = today - np.timedelta64(1, 'D')  # Вчера
tomorrow = today + np.timedelta64(1, 'D')  # Завтра

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-03-06
Today: 2025-03-07
Tomorrow: 2025-03-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
# np.arange(dtype=datetime64['D'])
start_date = np.datetime64('2016-06-01', 's')
end_date = np.datetime64('2016-07-01', 's')
np.arange(start_date, end_date, np.timedelta64('1', 'D'))


array(['2016-06-01T00:00:00', '2016-06-02T00:00:00',
       '2016-06-03T00:00:00', '2016-06-04T00:00:00',
       '2016-06-05T00:00:00', '2016-06-06T00:00:00',
       '2016-06-07T00:00:00', '2016-06-08T00:00:00',
       '2016-06-09T00:00:00', '2016-06-10T00:00:00',
       '2016-06-11T00:00:00', '2016-06-12T00:00:00',
       '2016-06-13T00:00:00', '2016-06-14T00:00:00',
       '2016-06-15T00:00:00', '2016-06-16T00:00:00',
       '2016-06-17T00:00:00', '2016-06-18T00:00:00',
       '2016-06-19T00:00:00', '2016-06-20T00:00:00',
       '2016-06-21T00:00:00', '2016-06-22T00:00:00',
       '2016-06-23T00:00:00', '2016-06-24T00:00:00',
       '2016-06-25T00:00:00', '2016-06-26T00:00:00',
       '2016-06-27T00:00:00', '2016-06-28T00:00:00',
       '2016-06-29T00:00:00', '2016-06-30T00:00:00'],
      dtype='datetime64[s]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
a = np.random.rand(10) * 10
print(np.floor(a))
print(a.astype(np.int64))
print(np.trunc(a))
print(a - a % 1)
print(a // 1)

[1. 9. 6. 3. 0. 9. 3. 5. 7. 3.]
[1 9 6 3 0 9 3 5 7 3]
[1. 9. 6. 3. 0. 9. 3. 5. 7. 3.]
[1. 9. 6. 3. 0. 9. 3. 5. 7. 3.]
[1. 9. 6. 3. 0. 9. 3. 5. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
np.zeros((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generator():
    for i in range(10):
        yield i


np.fromiter(generator(), int, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
np.linspace(0., 1, num=11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
a = np.random.random(10)
a.sort()
a


array([0.0322817 , 0.10382013, 0.11610824, 0.27511158, 0.3606241 ,
       0.4581004 , 0.52498741, 0.65946873, 0.66777282, 0.93248465])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
a = np.random.random(10)
np.add.reduce(a)

np.float64(6.214658261043205)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
a = np.random.random(10)
b = np.random.random(10)

np.allclose(a, b, rtol=1, atol=1)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
a = np.array([1, 2])
a.setflags(write=False)
a

array([1, 2])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.64206462 0.63672826 0.5203441  1.20226439 0.5228906  0.37680447
 0.30245651 0.36309522 1.01220035 0.61155372]
[0.69661564 0.23447693 1.0573267  0.61026889 1.17632768 0.63614279
 0.43862663 0.48029751 0.63103251 0.91782085]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
a = np.random.random((10))
a[a.argmax()] = 0
a

array([0.74764508, 0.0555794 , 0.70330889, 0.59347876, 0.14937727,
       0.02267033, 0.        , 0.75962899, 0.3878785 , 0.13729513])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
x = np.linspace(0, 1, 11)
y = np.linspace(0, 1, 11)

xv, yv = np.meshgrid(x, y)
xv + yv

# Z = np.zeros((5,5), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))
# Z

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1],
       [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2],
       [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3],
       [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4],
       [0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5],
       [0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
       [0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7],
       [0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8],
       [0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ]])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
# np.iinfo, np.finfo, eps
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

#### 49. How to print all the values of an array? (★★☆)

In [49]:


# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40, 40))
Z


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(40, 40))

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)